#include "web_assets.h"

const char *web_index_html(void)
{
    return
        "<!doctype html><html lang=\"zh-CN\"><head>"
        "<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        "<title>CellMgr</title><link rel=\"stylesheet\" href=\"/style.css\"></head>"
        "<body><aside><h1>CellMgr</h1><nav>"
        "<button data-view=\"overview\">概览</button>"
        "<button data-view=\"device\">设备监控</button>"
        "<button data-view=\"modem\">模组监控</button>"
        "<button data-view=\"network\">高级网络</button>"
        "<button data-view=\"sms\">短信</button>"
        "<button data-view=\"at\">AT 指令</button>"
        "<button data-view=\"settings\">系统设置</button>"
        "</nav></aside><main>"
        "<section id=\"overview\" class=\"view active\"><h2>模组概览</h2><div id=\"overviewGrid\" class=\"grid\"></div></section>"
        "<section id=\"device\" class=\"view\"><h2>设备监控</h2><pre id=\"deviceJson\"></pre><button id=\"dropCaches\">清理内存</button></section>"
        "<section id=\"modem\" class=\"view\"><h2>模组监控</h2><div class=\"row\"><button id=\"modemOnline\">上线</button><button id=\"modemOffline\">飞行模式</button><button id=\"modemPowerOn\">上电</button><button id=\"modemPowerOff\">断电</button><button id=\"dbusEvents\">D-Bus 事件</button></div><pre id=\"modemJson\"></pre></section>"
        "<section id=\"network\" class=\"view\"><h2>高级网络</h2>"
        "<div class=\"row\"><button id=\"discoverBands\">重新探测频段</button><button id=\"unlockNetwork\">解除锁定</button></div>"
        "<div class=\"row\"><input id=\"bandMode\" value=\"1\"><input id=\"bandRat\" value=\"17\"><input id=\"bandPref\" value=\"6\"><input id=\"bandList\" value=\"101,103,141\"><button id=\"lockBand\">锁频段</button></div>"
        "<div class=\"row\"><input id=\"cellRat\" value=\"0\"><input id=\"cellEarfcn\" value=\"1850\"><input id=\"cellPci\" value=\"123\"><button id=\"lockCell\">锁小区</button><button id=\"lockFrequency\">锁频点</button></div>"
        "<pre id=\"networkJson\"></pre></section>"
        "<section id=\"sms\" class=\"view\"><h2>短信管理</h2>"
        "<div class=\"row\"><button id=\"loadSms\">查看短信</button><input id=\"smsIndex\" value=\"1\"><button id=\"readSms\">读取</button><button id=\"deleteSms\">删除</button></div>"
        "<div class=\"row\"><input id=\"smsNumber\" placeholder=\"号码\"><input id=\"smsText\" placeholder=\"内容\"><button id=\"sendSms\">发送</button></div><pre id=\"smsJson\"></pre></section>"
        "<section id=\"at\" class=\"view\"><h2>AT 指令台</h2><div class=\"row\"><input id=\"atCommand\" value=\"AT+CSQ\"><button id=\"sendAt\">发送</button><button id=\"loadAtHistory\">历史</button></div><pre id=\"atOutput\"></pre></section>"
        "<section id=\"settings\" class=\"view\"><h2>系统设置</h2>"
        "<div class=\"settings-layout\"><div><h3>Profile</h3><div id=\"profileList\" class=\"profile-list\"></div>"
        "<div class=\"row\"><button id=\"newProfile\">新增</button><button id=\"reloadProfiles\">刷新</button></div></div>"
        "<div><h3>JSON</h3><textarea id=\"profileEditor\" spellcheck=\"false\"></textarea>"
        "<div class=\"row\"><button id=\"saveProfile\">保存</button><button id=\"activateProfile\">激活</button><button id=\"deleteProfile\">删除</button></div>"
        "<h3>设备参数</h3><div class=\"row\"><input id=\"ofonoPath\" value=\"/ril_0\"><input id=\"wanIface\" value=\"rmnet_data0\"><input id=\"atTimeout\" value=\"3000\"><input id=\"dangerousAt\" value=\"0\"></div>"
        "<h3>定时重启</h3><div class=\"row\"><input id=\"rebootHour\" value=\"3\"><input id=\"rebootMinute\" value=\"30\"><button id=\"saveSchedule\">保存定时</button><button id=\"rebootNow\">立即重启</button></div>"
        "<h3>短信转发</h3><div class=\"row\"><input id=\"forwardMode\" value=\"smtp\"><input id=\"smtpHost\" placeholder=\"SMTP host\"><input id=\"smtpPort\" value=\"25\"></div>"
        "<div class=\"row\"><input id=\"smtpUser\" placeholder=\"SMTP user\"><input id=\"smtpPass\" placeholder=\"SMTP pass\"><input id=\"smtpFrom\" placeholder=\"from\"><input id=\"smtpTo\" placeholder=\"to\"></div>"
        "<div class=\"row\"><input id=\"webhookUrl\" placeholder=\"HTTP webhook\"><button id=\"saveForward\">保存转发</button><button id=\"testForward\">测试转发</button></div>"
        "<pre id=\"settingsJson\"></pre></div></div></section>"
        "</main><script src=\"/app.js\"></script></body></html>";
}

const char *web_style_css(void)
{
    return
        ":root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#18212f;background:#eef2f6}"
        "*{box-sizing:border-box}body{margin:0;display:grid;grid-template-columns:220px 1fr;min-height:100vh}"
        "aside{background:#111827;color:#fff;padding:18px 14px}h1{font-size:20px;margin:0 0 18px}"
        "nav{display:grid;gap:6px}button{border:0;border-radius:6px;padding:9px 12px;background:#2563eb;color:#fff;cursor:pointer}"
        "nav button{background:transparent;color:#dbe4f0;text-align:left}nav button.active,nav button:hover{background:#243244;color:#fff}"
        "main{padding:20px;overflow:auto}h2{font-size:18px;margin:0 0 14px}.view{display:none}.view.active{display:block}"
        ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}"
        ".tile{background:#fff;border:1px solid #d8dee8;border-radius:8px;padding:12px;min-height:82px}"
        ".tile span{display:block;color:#5b677a;font-size:12px}.tile strong{display:block;margin-top:8px;font-size:20px;color:#111827}"
        "pre{background:#fff;border:1px solid #d8dee8;border-radius:8px;padding:12px;overflow:auto;min-height:120px}"
        "h3{font-size:14px;margin:0 0 10px;color:#364256}.settings-layout{display:grid;grid-template-columns:280px 1fr;gap:14px}"
        ".profile-list{display:grid;gap:6px;margin-bottom:10px}.profile-item{background:#fff;border:1px solid #d8dee8;border-radius:8px;padding:10px;text-align:left;color:#111827}"
        ".profile-item.active{border-color:#2563eb;box-shadow:inset 3px 0 0 #2563eb}.profile-item small{display:block;color:#6b7280;margin-top:4px}"
        "textarea{width:100%;min-height:420px;border:1px solid #c8d0dd;border-radius:8px;padding:10px;font:12px ui-monospace,SFMono-Regular,Consolas,monospace;background:#fff}"
        ".row{display:flex;gap:8px;margin-bottom:10px}input{flex:1;border:1px solid #c8d0dd;border-radius:6px;padding:9px 10px;font:inherit}"
        "@media(max-width:760px){body{display:block}aside{position:sticky;top:0;z-index:2}nav{grid-template-columns:repeat(4,1fr)}main{padding:14px}.settings-layout{grid-template-columns:1fr}}";
}

const char *web_app_js(void)
{
    return
        "const $=s=>document.querySelector(s);"
        "const fmt=o=>JSON.stringify(o,null,2);let selectedProfile='';let token=localStorage.cellmgrToken||'';"
        "function setv(s,v){let e=$(s);if(document.activeElement!==e)e.value=v??''}"
        "async function login(){let username=prompt('用户名','admin'),password=prompt('密码','');let r=await fetch('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})}).then(x=>x.json());if(r.ok){token=r.data.token;localStorage.cellmgrToken=token;return true}alert('登录失败');return false}"
        "async function api(p,o={}){o.headers=o.headers||{};if(token)o.headers['X-Cellmgr-Session']=token;const r=await fetch(p,o);let j=await r.json();if(!j.ok&&j.error==='unauthorized'){if(await login())return api(p,o)}return j}"
        "function tile(k,v){return `<div class=tile><span>${k}</span><strong>${v??'-'}</strong></div>`}"
        "document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{"
        "document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');"
        "document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');refresh()});"
        "document.querySelector('nav button').classList.add('active');"
        "async function loadProfiles(){let r=await api('/api/profiles').catch(e=>({ok:false,error:String(e)}));"
        "if(!r.ok){$('#profileList').textContent=r.error||'加载失败';return}"
        "$('#profileList').innerHTML=r.data.profiles.map(p=>`<button class=\"profile-item ${p.active?'active':''}\" data-id=\"${p.id}\">${p.name}<small>${p.id}${p.active?' · active':''}</small></button>`).join('');"
        "document.querySelectorAll('.profile-item').forEach(b=>b.onclick=()=>editProfile(b.dataset.id));"
        "let a=r.data.profiles.find(p=>p.active)||r.data.profiles[0];if(a&&!selectedProfile)editProfile(a.id)}"
        "async function editProfile(id){selectedProfile=id;let r=await api('/api/profiles/get?id='+encodeURIComponent(id));"
        "$('#profileEditor').value=r.ok?fmt(r.data):fmt(r);}"
        "async function saveProfile(){let txt=$('#profileEditor').value;try{JSON.parse(txt)}catch(e){$('#settingsJson').textContent='JSON 格式错误: '+e.message;return}"
        "let r=await api('/api/profiles/save',{method:'POST',headers:{'Content-Type':'application/json'},body:txt});$('#settingsJson').textContent=fmt(r);if(r.ok){selectedProfile=r.data.id;await loadProfiles()}}"
        "async function activateProfile(){let txt=$('#profileEditor').value,id=selectedProfile;try{id=JSON.parse(txt).id||id}catch(e){}"
        "let r=await api('/api/profiles/activate',{method:'POST',body:JSON.stringify({id})});$('#settingsJson').textContent=fmt(r);if(r.ok){await loadProfiles()}}"
        "async function deleteProfile(){let id=selectedProfile;if(!id||!confirm('删除 profile '+id+' ?'))return;"
        "let r=await api('/api/profiles/delete',{method:'POST',body:JSON.stringify({id})});$('#settingsJson').textContent=fmt(r);if(r.ok){selectedProfile='';$('#profileEditor').value='';await loadProfiles()}}"
        "function newProfile(){selectedProfile='';$('#profileEditor').value=fmt({schema_version:1,id:'new-profile',name:'New Profile',default_modem_path:'/ril_0',at_backend:'ofono-sendatcmd',capabilities:{}})}"
        "async function refresh(){"
        "let ov=await api('/api/overview').catch(e=>({ok:false,error:String(e)}));"
        "if(ov.ok){let d=ov.data.device;$('#overviewGrid').innerHTML=["
        "tile('CPU',d.cpu_percent.toFixed(1)+'%'),tile('内存可用',Math.round(d.mem_available_kb/1024)+' MB'),"
        "tile('磁盘可用',Math.round(d.disk_free_bytes/1048576)+' MB'),tile('温度',d.temperature_c===null?'-':d.temperature_c+' C'),"
        "tile('WAN',d.wan_iface),tile('RX/TX',d.rx_bytes+'/'+d.tx_bytes)].join('')}"
        "$('#deviceJson').textContent=fmt(ov);"
        "let m=await api('/api/modem/status').catch(e=>({ok:false,error:String(e)}));let r=await api('/api/modem/radio').catch(e=>({ok:false,error:String(e)}));$('#modemJson').textContent=fmt({status:m,radio:r});"
        "let s=await api('/api/system/settings').catch(e=>({ok:false,error:String(e)}));$('#settingsJson').textContent=fmt(s);if(s.ok){let d=s.data;setv('#ofonoPath',d.ofono_modem_path||'/ril_0');setv('#wanIface',d.wan_iface||'');setv('#atTimeout',d.at_timeout_ms||3000);setv('#dangerousAt',d.allow_dangerous_at||0);setv('#rebootHour',d.scheduled_reboot_hour);setv('#rebootMinute',d.scheduled_reboot_minute);setv('#forwardMode',d.sms_forward_mode||'smtp');setv('#smtpHost',d.smtp_host||'');setv('#smtpPort',d.smtp_port||25);setv('#smtpUser',d.smtp_user||'');setv('#smtpFrom',d.smtp_from||'');setv('#smtpTo',d.smtp_to||'');setv('#webhookUrl',d.sms_webhook_url||'');}}"
        "$('#sendAt').onclick=async()=>{$('#atOutput').textContent='发送中...';let r=await api('/api/at/send',{method:'POST',body:JSON.stringify({command:$('#atCommand').value})});$('#atOutput').textContent=fmt(r)};"
        "$('#loadAtHistory').onclick=async()=>{$('#atOutput').textContent=fmt(await api('/api/at/history?limit=30'))};"
        "$('#dropCaches').onclick=async()=>{$('#deviceJson').textContent=fmt(await api('/api/device/drop-caches',{method:'POST',body:'{}'}));};"
        "$('#modemOnline').onclick=async()=>{$('#modemJson').textContent=fmt(await api('/api/modem/online',{method:'POST',body:JSON.stringify({confirm:true,online:1})}))};"
        "$('#modemOffline').onclick=async()=>{$('#modemJson').textContent=fmt(await api('/api/modem/online',{method:'POST',body:JSON.stringify({confirm:true,online:0})}))};"
        "$('#modemPowerOn').onclick=async()=>{$('#modemJson').textContent=fmt(await api('/api/modem/power',{method:'POST',body:JSON.stringify({confirm:true,powered:1})}))};"
        "$('#modemPowerOff').onclick=async()=>{if(confirm('关闭模组电源?'))$('#modemJson').textContent=fmt(await api('/api/modem/power',{method:'POST',body:JSON.stringify({confirm:true,powered:0})}))};"
        "$('#dbusEvents').onclick=async()=>{$('#modemJson').textContent=fmt(await api('/api/system/dbus/events?limit=80'))};"
        "$('#discoverBands').onclick=async()=>{$('#networkJson').textContent='探测中...';$('#networkJson').textContent=fmt(await api('/api/network/bands?refresh=1'));};"
        "$('#lockBand').onclick=async()=>{$('#networkJson').textContent=fmt(await api('/api/network/lock-band',{method:'POST',body:JSON.stringify({confirm:true,mode:$('#bandMode').value,rat:$('#bandRat').value,preferred_rat:$('#bandPref').value,bands:$('#bandList').value})}))};"
        "$('#lockCell').onclick=async()=>{$('#networkJson').textContent=fmt(await api('/api/network/lock-cell',{method:'POST',body:JSON.stringify({confirm:true,rat:+$('#cellRat').value,earfcn:+$('#cellEarfcn').value,pci:+$('#cellPci').value})}))};"
        "$('#lockFrequency').onclick=async()=>{$('#networkJson').textContent=fmt(await api('/api/network/lock-frequency',{method:'POST',body:JSON.stringify({confirm:true,rat:+$('#cellRat').value,earfcn:+$('#cellEarfcn').value})}))};"
        "$('#unlockNetwork').onclick=async()=>{if(confirm('解除网络锁定?'))$('#networkJson').textContent=fmt(await api('/api/network/unlock',{method:'POST',body:JSON.stringify({confirm:true})}))};"
        "$('#loadSms').onclick=async()=>{$('#smsJson').textContent=fmt(await api('/api/sms/list'))};"
        "$('#readSms').onclick=async()=>{$('#smsJson').textContent=fmt(await api('/api/sms/read?index='+encodeURIComponent($('#smsIndex').value)))};"
        "$('#deleteSms').onclick=async()=>{if(confirm('删除短信 '+$('#smsIndex').value+' ?'))$('#smsJson').textContent=fmt(await api('/api/sms/delete',{method:'POST',body:JSON.stringify({confirm:true,index:+$('#smsIndex').value})}))};"
        "$('#sendSms').onclick=async()=>{$('#smsJson').textContent=fmt(await api('/api/sms/send',{method:'POST',body:JSON.stringify({number:$('#smsNumber').value,text:$('#smsText').value})}))};"
        "$('#saveProfile').onclick=saveProfile;$('#activateProfile').onclick=activateProfile;$('#deleteProfile').onclick=deleteProfile;$('#newProfile').onclick=newProfile;$('#reloadProfiles').onclick=loadProfiles;"
        "$('#saveSchedule').onclick=async()=>{$('#settingsJson').textContent=fmt(await api('/api/system/scheduled-reboot',{method:'POST',body:JSON.stringify({enabled:true,hour:+$('#rebootHour').value,minute:+$('#rebootMinute').value})}))};"
        "$('#saveForward').onclick=async()=>{$('#settingsJson').textContent=fmt(await api('/api/system/settings-save',{method:'POST',body:JSON.stringify({ofono_modem_path:$('#ofonoPath').value,wan_iface:$('#wanIface').value,at_timeout_ms:+$('#atTimeout').value,allow_dangerous_at:+$('#dangerousAt').value,sms_forward_enabled:1,sms_forward_mode:$('#forwardMode').value,smtp_host:$('#smtpHost').value,smtp_port:+$('#smtpPort').value,smtp_user:$('#smtpUser').value,smtp_pass:$('#smtpPass').value,smtp_from:$('#smtpFrom').value,smtp_to:$('#smtpTo').value,sms_webhook_url:$('#webhookUrl').value})}))};"
        "$('#testForward').onclick=async()=>{$('#settingsJson').textContent=fmt(await api('/api/sms/forward-test',{method:'POST',body:JSON.stringify({from:'test',text:'CellMgr test SMS'})}))};"
        "$('#rebootNow').onclick=async()=>{if(confirm('立即重启设备?'))$('#settingsJson').textContent=fmt(await api('/api/system/reboot',{method:'POST',body:JSON.stringify({confirm:true})}))};"
        "setInterval(refresh,3000);loadProfiles();refresh();";
}
